### ISSUE TITLE
Issues persist similar to women's program

### ISSUE THREAD

**Issue by mountaingoat69** [WebCab-Design/mens.peaksrecovery.com#1]
@TheBurnsby 
Please ad admissions tab to main menu so it reads: Home-Recovery Program-Admissions-Contact

Also, I changed verbiage for admissions pages and treatment philosophy. None of which are showing up in localhost. Maybe linking issues? 

Also changed verbiage on layout page, specifically footer section and not seeing that on localhost view either.

**Comment by xeaone** [comment]
- Moved Admissions to the menu
- I am thinking you will need to empty your dist directory then muleify it again.
- Fixed the links on all pages including Mental Health and Addiction Treatment pages.

If the verbiage is not showing up feel free to post it here and where it needs to go.
